routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (Auth::check()) 
    {
        return view('home');
    }
    else
    {
        return view('auth.login');
    }
});

/** Carga home por defecto */
Route::get('/home', function () {
    if (Auth::check()) 
    {
        return view('home');
    }
    else
    {
        return view('auth.login');
    }
});

Auth::routes();

/** Acceso a la gestión de alumnos */
Route::resource('alumnos', App\Http\Controllers\AlumnoController::class)->middleware('auth');

/** Acceso a la gestión de asignaturas */
Route::resource('asignaturas', App\Http\Controllers\AsignaturaController::class)->middleware('auth');

/** Acceso a la gestión de convocatorias */
Route::resource('convocatorias', App\Http\Controllers\ConvocatoriaController::class)->middleware('auth');

/** Acceso a la gestión de matriculaciones */
Route::resource('matriculaciones', App\Http\Controllers\MatriculacioneController::class)->middleware('auth');

/** Acceso a la gestión de calificaciones */
Route::resource('calificaciones', App\Http\Controllers\CalificacioneController::class)->middleware('auth');

app/Models/Calificacione.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Calificacione
 *
 * @property $id
 * @property $alumno_id
 * @property $asignatura_id
 * @property $convocatoria_id
 * @property $calificacion
 * @property $created_at
 * @property $updated_at
 *
 * @property Alumno $alumno
 * @property Asignatura $asignatura
 * @property Convocatoria $convocatoria
 * @package App
 * @mixin \Illuminate\Database\Eloquent\Builder
 */
class Calificacione extends Model
{
    
    static $rules = [
		'alumno_id' => 'required',
		'asignatura_id' => 'required',
		'convocatoria_id' => 'required',
		'calificacion' => 'required',
    ];

    protected $perPage = 20;

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['alumno_id','asignatura_id','convocatoria_id','calificacion'];


    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function alumno()
    {
        return $this->hasOne('App\Models\Alumno', 'id', 'alumno_id');
    }
    
    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function asignatura()
    {
        return $this->hasOne('App\Models\Asignatura', 'id', 'asignatura_id');
    }
    
    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function convocatoria()
    {
        return $this->hasOne('App\Models\Convocatoria', 'id', 'convocatoria_id');
    }
    

}

app/Http/Controllers/CalificacioneController.php
<?php

namespace App\Http\Controllers;

use App\Models\Calificacione;
use App\Models\Alumno;
use App\Models\Asignatura;
use App\Models\Convocatoria;
use Illuminate\Http\Request;

/**
 * Class CalificacioneController
 * @package App\Http\Controllers
 */
class CalificacioneController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $calificaciones = Calificacione::paginate();

        return view('calificacione.index', compact('calificaciones'))
            ->with('i', (request()->input('page', 1) - 1) * $calificaciones->perPage());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $calificacione = new Calificacione();
        $alumnos       = Alumno::pluck('nombre','id');
        $asignaturas   = Asignatura::pluck('nombre','id');
        $convocatorias = Convocatoria::pluck('nombre','id');
        return view('calificacione.create', compact('calificacione','alumnos','asignaturas','convocatorias'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate(Calificacione::$rules);

        $calificacione = Calificacione::create($request->all());

        return redirect()->route('calificaciones.index')
            ->with('success', 'Calificacione created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $calificacione = Calificacione::find($id);

        return view('calificacione.show', compact('calificacione'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $calificacione = Calificacione::find($id);
        $alumnos       = Alumno::pluck('nombre','id');
        $asignaturas   = Asignatura::pluck('nombre','id');
        $convocatorias = Convocatoria::pluck('nombre','id');
        return view('calificacione.edit', compact('calificacione','alumnos','asignaturas','convocatorias'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  Calificacione $calificacione
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Calificacione $calificacione)
    {
        request()->validate(Calificacione::$rules);

        $calificacione->update($request->all());

        return redirect()->route('calificaciones.index')
            ->with('success', 'Calificacione updated successfully');
    }

    /**
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy($id)
    {
        $calificacione = Calificacione::find($id)->delete();

        return redirect()->route('calificaciones.index')
            ->with('success', 'Calificacione deleted successfully');
    }
}

resources/views/calificacione/create.blade.php
@extends('layouts.app')

@section('template_title')
    Create Calificacione
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">Añadir calificación</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('calificaciones.store') }}"  role="form" enctype="multipart/form-data">
                            @csrf

                            @include('calificacione.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/calificacione/edit.blade.php
@extends('layouts.app')

@section('template_title')
    Update Calificacione
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">Editar Calificación</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('calificaciones.update', $calificacione->id) }}"  role="form" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            @csrf

                            @include('calificacione.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/calificacione/form.blade.php
<div class="box box-info padding-1">
    <div class="box-body">
        
        <div class="form-group">
            {{ Form::label('Alumno') }}
            {{ Form::select('alumno_id', $alumnos, $calificacione->alumno_id, ['class' => 'form-control' . ($errors->has('alumno_id') ? ' is-invalid' : ''), 'placeholder' => 'Alumno']) }}
            {!! $errors->first('alumno_id', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('Asignatura') }}
            {{ Form::select('asignatura_id', $asignaturas, $calificacione->asignatura_id, ['class' => 'form-control' . ($errors->has('asignatura_id') ? ' is-invalid' : ''), 'placeholder' => 'Asignatura']) }}
            {!! $errors->first('asignatura_id', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('Convocatoria') }}
            {{ Form::select('convocatoria_id', $convocatorias, $calificacione->convocatoria_id, ['class' => 'form-control' . ($errors->has('convocatoria_id') ? ' is-invalid' : ''), 'placeholder' => 'Convocatoria']) }}
            {!! $errors->first('convocatoria_id', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('Calificación') }}
            {{ Form::text('calificacion', $calificacione->calificacion, ['class' => 'form-control' . ($errors->has('calificacion') ? ' is-invalid' : ''), 'placeholder' => 'Calificación']) }}
            {!! $errors->first('calificacion', '<div class="invalid-feedback">:message</div>') !!}
        </div>

    </div>
    <div class="box-footer mt-2">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</div>

resources/views/calificacione/index.blade.php
@extends('layouts.app')

@section('template_title')
    Calificacione
@endsection

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <div style="display: flex; justify-content: space-between; align-items: center;">

                            <span id="card_title">
                                {{ __('Calificaciones') }}
                            </span>

                             <div class="float-right">
                                <a href="{{ route('calificaciones.create') }}" class="btn btn-primary btn-sm float-right"  data-placement="left">
                                  {{ __('Añadir') }}
                                </a>
                              </div>
                        </div>
                    </div>
                    @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <p>{{ $message }}</p>
                        </div>
                    @endif

                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-striped table-hover">
                                <thead class="thead">
                                    <tr>
                                        <th>No</th>
                                        
										<th>Alumno</th>
										<th>Asignatura</th>
										<th>Convocatoria</th>
										<th>Calificacion</th>

                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($calificaciones as $calificacione)
                                        <tr>
                                            <td>{{ $calificacione->id }}</td>
                                            
											<td>{{ $calificacione->alumno->nombre }}</td>
											<td>{{ $calificacione->asignatura->nombre }}</td>
											<td>{{ $calificacione->convocatoria->nombre }}</td>
											<td>{{ $calificacione->calificacion }}</td>

                                            <td>
                                                <form action="{{ route('calificaciones.destroy',$calificacione->id) }}" method="POST">
                                                    <a class="btn btn-sm btn-primary " href="{{ route('calificaciones.show',$calificacione->id) }}"><i class="fa fa-fw fa-eye"></i> Mostrar</a>
                                                    <a class="btn btn-sm btn-success" href="{{ route('calificaciones.edit',$calificacione->id) }}"><i class="fa fa-fw fa-edit"></i> Editar</a>
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" class="btn btn-danger btn-sm"><i class="fa fa-fw fa-trash"></i> Eliminar</button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                {!! $calificaciones->links() !!}
            </div>
        </div>
    </div>
@endsection

resources/views/calificacione/show.blade.php
@extends('layouts.app')

@section('template_title')
    {{ $calificacione->name ?? 'Show Calificacione' }}
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="float-left">
                            <span class="card-title">Show Calificacione</span>
                        </div>
                        <div class="float-right">
                            <a class="btn btn-primary" href="{{ route('calificaciones.index') }}"> Back</a>
                        </div>
                    </div>

                    <div class="card-body">
                        
                        <div class="form-group">
                            <strong>Alumno Id:</strong>
                            {{ $calificacione->alumno_id }}
                        </div>
                        <div class="form-group">
                            <strong>Asignatura Id:</strong>
                            {{ $calificacione->asignatura_id }}
                        </div>
                        <div class="form-group">
                            <strong>Convocatoria Id:</strong>
                            {{ $calificacione->convocatoria_id }}
                        </div>
                        <div class="form-group">
                            <strong>Calificacion:</strong>
                            {{ $calificacione->calificacion }}
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection