routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (Auth::check()) 
    {
        return view('home');
    }
    else
    {
        return view('auth.login');
    }
});

/** Carga home por defecto */
Route::get('/home', function () {
    if (Auth::check()) 
    {
        return view('home');
    }
    else
    {
        return view('auth.login');
    }
});

Auth::routes();

/** Acceso a la gestión de alumnos */
Route::resource('alumnos', App\Http\Controllers\AlumnoController::class)->middleware('auth');

/** Acceso a la gestión de asignaturas */
Route::resource('asignaturas', App\Http\Controllers\AsignaturaController::class)->middleware('auth');

/** Acceso a la gestión de convocatorias */
Route::resource('convocatorias', App\Http\Controllers\ConvocatoriaController::class)->middleware('auth');

/** Acceso a la gestión de matriculaciones */
Route::resource('matriculaciones', App\Http\Controllers\MatriculacioneController::class)->middleware('auth');

/** Acceso a la gestión de calificaciones */
Route::resource('calificaciones', App\Http\Controllers\CalificacioneController::class)->middleware('auth');

app/Models/Convocatoria.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Convocatoria
 *
 * @property $id
 * @property $nombre
 * @property $created_at
 * @property $updated_at
 *
 * @property Calificacione[] $calificaciones
 * @package App
 * @mixin \Illuminate\Database\Eloquent\Builder
 */
class Convocatoria extends Model
{
    
    static $rules = [
		'nombre' => 'required',
    ];

    protected $perPage = 20;

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['nombre'];


    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function calificaciones()
    {
        return $this->hasMany('App\Models\Calificacione', 'convocatoria_id', 'id');
    }
    

}

app/Http/Controllers/ConvocatoriaController.php
<?php

namespace App\Http\Controllers;

use App\Models\Convocatoria;
use Illuminate\Http\Request;

/**
 * Class ConvocatoriaController
 * @package App\Http\Controllers
 */
class ConvocatoriaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $convocatorias = Convocatoria::paginate();

        return view('convocatoria.index', compact('convocatorias'))
            ->with('i', (request()->input('page', 1) - 1) * $convocatorias->perPage());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $convocatoria = new Convocatoria();
        return view('convocatoria.create', compact('convocatoria'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate(Convocatoria::$rules);

        $convocatoria = Convocatoria::create($request->all());

        return redirect()->route('convocatorias.index')
            ->with('success', 'Convocatoria created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $convocatoria = Convocatoria::find($id);

        return view('convocatoria.show', compact('convocatoria'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $convocatoria = Convocatoria::find($id);

        return view('convocatoria.edit', compact('convocatoria'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  Convocatoria $convocatoria
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Convocatoria $convocatoria)
    {
        request()->validate(Convocatoria::$rules);

        $convocatoria->update($request->all());

        return redirect()->route('convocatorias.index')
            ->with('success', 'Convocatoria updated successfully');
    }

    /**
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy($id)
    {
        $convocatoria = Convocatoria::find($id)->delete();

        return redirect()->route('convocatorias.index')
            ->with('success', 'Convocatoria deleted successfully');
    }
}

resources/views/convocatoria/create.blade.php
@extends('layouts.app')

@section('template_title')
    Create Convocatoria
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">Añadir convocatoria</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('convocatorias.store') }}"  role="form" enctype="multipart/form-data">
                            @csrf

                            @include('convocatoria.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/convocatoria/edit.blade.php
@extends('layouts.app')

@section('template_title')
    Update Convocatoria
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">Editar convocatoria</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('convocatorias.update', $convocatoria->id) }}"  role="form" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            @csrf

                            @include('convocatoria.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/convocatoria/form.blade.php
<div class="box box-info padding-1">
    <div class="box-body">
        
        <div class="form-group">
            {{ Form::label('nombre') }}
            {{ Form::text('nombre', $convocatoria->nombre, ['class' => 'form-control' . ($errors->has('nombre') ? ' is-invalid' : ''), 'placeholder' => 'Nombre']) }}
            {!! $errors->first('nombre', '<div class="invalid-feedback">:message</div>') !!}
        </div>

    </div>
    <div class="box-footer mt-2">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</div>

resources/views/convocatoria/index.blade.php
@extends('layouts.app')

@section('template_title')
    Convocatoria
@endsection

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <div style="display: flex; justify-content: space-between; align-items: center;">

                            <span id="card_title">
                                {{ __('Convocatorias') }}
                            </span>

                             <div class="float-right">
                                <a href="{{ route('convocatorias.create') }}" class="btn btn-primary btn-sm float-right"  data-placement="left">
                                  {{ __('Añadir') }}
                                </a>
                              </div>
                        </div>
                    </div>
                    @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <p>{{ $message }}</p>
                        </div>
                    @endif

                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-striped table-hover">
                                <thead class="thead">
                                    <tr>
                                        <th>No</th>
                                        
										<th>Nombre</th>

                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($convocatorias as $convocatoria)
                                        <tr>
                                            <td>{{ ++$i }}</td>
                                            
											<td>{{ $convocatoria->nombre }}</td>

                                            <td>
                                                <form action="{{ route('convocatorias.destroy',$convocatoria->id) }}" method="POST">
                                                    <a class="btn btn-sm btn-primary " href="{{ route('convocatorias.show',$convocatoria->id) }}"><i class="fa fa-fw fa-eye"></i> Mostrar</a>
                                                    <a class="btn btn-sm btn-success" href="{{ route('convocatorias.edit',$convocatoria->id) }}"><i class="fa fa-fw fa-edit"></i> Editar</a>
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" class="btn btn-danger btn-sm"><i class="fa fa-fw fa-trash"></i> Eliminar</button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                {!! $convocatorias->links() !!}
            </div>
        </div>
    </div>
@endsection

resources/views/convocatoria/show.blade.php
@extends('layouts.app')

@section('template_title')
    {{ $convocatoria->name ?? 'Show Convocatoria' }}
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="float-left">
                            <span class="card-title">Show Convocatoria</span>
                        </div>
                        <div class="float-right">
                            <a class="btn btn-primary" href="{{ route('convocatorias.index') }}"> Back</a>
                        </div>
                    </div>

                    <div class="card-body">
                        
                        <div class="form-group">
                            <strong>Nombre:</strong>
                            {{ $convocatoria->nombre }}
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection